---
openapi: 3.0.3
info:
  title: onecx-theme-bff
  description: OneCx theme Bff
  version: "1.0"
servers:
  - url: http://onecx-theme-bff:8080/
tags:
  - name: theme
paths:
  /themes:
    get:
      tags:
        - themes
      description: Find all themes
      operationId: getThemes
      parameters:
        - name: pageNumber
          in: query
          schema:
            format: int32
            description: The number of page.
            default: 0
            type: integer
        - name: pageSize
          in: query
          schema:
            format: int32
            description: The size of page
            default: 100
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetThemesResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
    post:
      tags:
        - themes
      description: Create theme
      operationId: createTheme
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateThemeRequest'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateThemeResponse'
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
  /themes/{id}:
    get:
      tags:
        - themes
      description: Find theme by id
      operationId: getThemeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetThemeResponse'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
    put:
      tags:
        - themes
      description: Update theme
      operationId: updateTheme
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateThemeRequest'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateThemeResponse'
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
    delete:
      tags:
        - themes
      description: Delete theme
      operationId: deleteTheme
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
  /themes/search:
    post:
      tags:
        - themes
      description: Search themes by criteria
      operationId: searchThemes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchThemeRequest'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchThemeResponse'
        "204":
          description: No Content
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestException'
components:
  schemas:
    Theme:
      type: object
      properties:
        version:
          format: int32
          type: integer
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
        id:
          type: string
        name:
          minLength: 2
          type: string
        cssFile:
          type: string
        description:
          type: string
        assetsUrl:
          type: string
        logoUrl:
          type: string
        faviconUrl:
          type: string
        previewImageUrl:
          type: string
        assetsUpdateDate:
          type: string
        properties:
          type: object
        portals:
          type: array
          items:
            type: object
    GetThemeResponse:
      required:
        - resource
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/Theme'
    GetThemesResponse:
      type: object
      properties:
        totalElements:
          format: int32
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int32
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/Theme'
    CreateThemeResponse:
      required:
        - resource
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/Theme'
    UpdateThemeResponse:
      required:
        - resource
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/Theme'
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
    RestException:
      type: object
      properties:
        errorCode:
          type: string
        message:
          type: string
        parameters:
          type: array
          items:
            type: object
        namedParameters:
          type: object
          additionalProperties:
            type: object
        validations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationConstraint'
    ValidationConstraint:
      type: object
      properties:
        parameter:
          type: string
        message:
          type: string
    CreateThemeRequest:
      required:
        - resource
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/Theme'
    UpdateThemeRequest:
      required:
        - resource
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/Theme'
    SearchThemeRequest:
      type: object
      properties:
        resource:
          $ref: '#/components/schemas/Theme'
    SearchThemeResponse:
      type: object
      properties:
        totalElements:
          format: int32
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int32
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/Theme'